### PR TITLE
Update runtime to 40, application to git, update dbus-python a bit

### PR DESCRIPTION
**Pull request by lionirdeadman**
This application being changed to git will **need** testing.

I've changed to git because :

It has python 3 fixes (#4)
It handles the presence of gtk4

### CODE REVIEW

**Comment by barthalion** [comment]
cc @tchx84

**Comment by tchx84** [comment]
A few comments:

* The media palette is broken (it's a regression, see images below)

image

vs

image

```
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/TurtleArt/tawindow.py", line 1241, in _buttonpress_cb
    self.button_press(
  File "/app/lib/python3.8/site-packages/TurtleArt/tawindow.py", line 1311, in button_press
    elif self._check_for_anything_else(spr, x, y):
  File "/app/lib/python3.8/site-packages/TurtleArt/tawindow.py", line 1624, in _check_for_anything_else
    self._select_category(spr)
  File "/app/lib/python3.8/site-packages/TurtleArt/tawindow.py", line 1794, in _select_category
    self.show_palette(i)
  File "/app/lib/python3.8/site-packages/TurtleArt/tawindow.py", line 987, in show_palette
    self.show_toolbar_palette(n)
  File "/app/lib/python3.8/site-packages/TurtleArt/tawindow.py", line 1097, in show_toolbar_palette
    self.palette_views[n].create(regenerate=regenerate, show=show)
  File "/app/lib/python3.8/site-packages/TurtleArt/tapaletteview.py", line 64, in create
    self._create_proto_blocks()
  File "/app/lib/python3.8/site-packages/TurtleArt/tapaletteview.py", line 198, in _create_proto_blocks
    self._proto_skin(name + 'small', self.blocks[-1].spr)
  File "/app/lib/python3.8/site-packages/TurtleArt/tapaletteview.py", line 211, in _proto_skin
    x, y = self._turtle_window.calc_image_offset(name, spr)
  File "/app/lib/python3.8/site-packages/TurtleArt/tawindow.py", line 4863, in calc_image_offset
    iw = self.media_shapes[name].get_width()
KeyError: 'camera1small'

```

@lionirdeadman  can you create an upstream issue? https://github.com/sugarlabs/turtleart-activity/issues 

* Numpy is still missing.

```
Failed to load Audio_sensors: No module named 'numpy'
```

This should be an easy fix https://github.com/flathub/org.sugarlabs.Speak/blob/master/org.sugarlabs.Speak.json#L27

**Comment by bbhtt** [comment]
Hello anyone working on this? 40 is EOL, so ideally the runtime should be bumped to 42 now and the dependencies needs to updated again.

**Comment by barthalion** [comment]
No idea if said regression has been fixed. @tchx84?

**Comment by nedrichards** [comment]
There's newer git commits upstream at the very least.

**Comment by wjt** [comment]
#7 updates to the 42 runtime, and a newer Git snapshot.

**Comment by wjt** [comment]
This can be closed, #7 was merged.

**Pull request closed without merging**
